version: '3.9'

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  api: 
    build: .
    ports:
      - 3000:3000
    environment:
      PORT : 3000
      DB_URL : 'mongodb://mongo_db:27017/elearnify' 
    env_file:
      - .env
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}